version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: usuario
      DB_PASSWORD: senhadobanco
      DB_NAME: usuario
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BROKER: kafka:9092
      REDIS_DNS: redis://redis:6379
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
      - kafka

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senhadobanco
      POSTGRES_DB: usuario
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=mypassword
      - REDIS_DNS=redis://:mypassword@redis:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3

  zookeeper:
    image: bitnami/zookeeper:latest  
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: "yes" 
    ports:
      - '2181:2181'
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:latest  
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # Ajustado
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT  # Ajustado para o único listener
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 1000
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_PORT: 9092
      KAFKA_LISTENER_HOST: 0.0.0.0  # Ajustado para aceitar todas interfaces
      KAFKA_LISTENER_INTERFACE: 0.0.0.0  # Ajustado para aceitar todas interfaces
      KAFKA_REPLICATION_FACTOR: 1  
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"  # Criação automática de tópicos
      KAFKA_NUM_PARTITIONS: 1   # Número de partições padrão
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1   # Fator de replicação padrão
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data
    restart: always   # Garante a reinicialização automática do broker

volumes:
  db_data:
  zookeeper_data:
  zookeeper_log:
  kafka_data:
